# Generated by Django 4.1.7 on 2023-04-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
